public class Data {

    static String[][] episodes = {
            {"Pilot", "Diversity Day", "Health Care", "The Alliance", "Basketball", "Hot Girl"},
            {"The Dundies", "Sexual Harassment", "Office Olympics", "The Fire", "Halloween",
                    "The Fight", "The Client", "Performance Review", "Email Surveillance", "Christmas Party",
                    "Booze Cruise", "The Injury", "The Secret", "The Carpet", "Boys and Girls",
                    "Valentine's Day", "Dwight's Speech", "Take Your Daughter To Work Day", "Michael's Birthday",
                    "Drug Testing", "Conflict Resolution", "Casino Night"},
            {"Gay Witch Hunt", "The Convention", "The Coup", "Grief Counseling", "Initiation", "Diwali",
                    "Branch Closing", "The Merger", "The Convict", "A Benihana Christmas Part 1", "A Benihana Christmas Part 2",
                    "Back From Vacation", "Traveling Salesmen", "The Return", "Ben Franklin", "Phyllis' Wedding",
                    "Business School", "Cocktails", "The Negotiation", "Safety Training", "Product Recall",
                    "Women's Appreciation", "Beach Games", "The Job Part 1", "The Job Part 2"},
            {"Fun Run", "Dunder Mifflin Infinity", "Launch Party", "Money", "Local Ad", "Branch Wars", "Survivor Man",
                    "The Deposition", "Dinner Party", "The Chair Model", "Night Out", "Did I Stutter", "Job Fair", "Goodbye, Toby"},
            {"Weight Loss", "Business Ethics", "Baby Shower", "Crime Aid", "Employee Transfer", "Customer Survey", "Business Trip",
                    "Frame Toby", "The Surplus", "Moroccan Christmas", "The Duel", "Prince Family Paper", "Stress Relief",
                    "Lecture Circuit Part 1", "Lecture Circuit Part 2", "Blood Drive", "Golden Ticket", "New Boss", "Two Weeks",
                    "Dream Team", "Michael Scott Paper Company", "Heavy Competition", "Broke", "Casual Friday", "Cafe Disco",
                    "Company Picnic"},
            {"Gossip", "The Meeting", "The Promotion", "Niagara", "Mafia", "The Lover", "Koi Pond", "Double Date", "Murder",
                    "Shareholder's Meeting", "Scott's Tots", "Secret Santa", "The Banker", "Sabre", "Manager and Salesman",
                    "The Delivery Part 1", "The Delivery Part 2", "St. Patrick's Day", "New Leads", "Happy Hour", "Secretary's Day",
                    "Body Language", "The Cover-Up", "The Chump", "Whistleblower"},
            {"Nepotism", "Counseling", "Andy's Play", "Sex Ed", "The Sting", "Costume Contest", "Christening", "Viewing Party",
                    "Wuphf.com", "China", "Classy Christmas Part 1", "Classy Christmas Part 2", "Ultimatum", "The Seminar",
                    "The Search", "PDA", "Threat Level Midnight", "Todd Packer", "Garage Sale", "Training Day", "Michael's Last Dundies",
                    "Goodbye, Michael", "The Inner Circle", "DKS, (Acting) Manager", "Search Committee"},
            {"The List", "The Incentive", "Lotto", "Garden Party", "Spooked", "Doomsday", "Pam's Replacement", "Gettysburg",
                    "Mrs. California", "Christmas Wishes", "Trivia", "Pool Party", "Jury Duty", "Special Project", "Tallahassee",
                    "After Hours", "Test The Store", "Last Day In Florida", "Get The Girl", "Welcome Party", "Angry Andy",
                    "Fundraiser", "Turf War", "Free Family Portrait Studio"},
            {"The New Guys", "Roy's Wedding", "Andy's Ancestry", "Work Bus", "Here Comes Treble", "The Boat", "The Whale",
                    "The Target", "Dwight Christmas", "Lice", "Suit Warehouse", "Customer Loyalty", "Junior Salesman", "Vandalism",
                    "Couples Discount", "Moving On", "The Farm", "Promos", "Stairmageddon", "Paper Airplane", "Livin' the Dream",
                    "A.A.R.M.", "Finale =("}
    };
    static String[][] desc = {
            {"<html>The premiere episode introduces the boss and<br>staff of the Dunder-Mifflin Paper Company in<br>Scranton, Pennsylvania in a documentary about<br>the workplace.</html>",
                    "<html>Michael's off color remark puts a sensitivity<br>trainer in the office for a presentation,<br>which prompts Michael to create his own.</html>",
                    "<html>Michael leaves Dwight in charge of picking<br>the new healthcare plan for the staff, with<br>disastrous results ahead.</html>",
                    "<html>Just for a laugh, Jim agrees to an alliance<br>with Dwight regarding the downsizing rumors.</html>",
                    "<html>Michael and his staff challenge the warehouse<br>workers to a basketball game with a bet<br>looming over both parties.</html>",
                    "<html>Michael is just one of the many male staff<br>who start vying for the attention of an<br>attractive saleswoman in the office.</html>"},

            {"<html>Very much unlike his staff, an overeager<br>Michael can't wait for this year's annual<br>Dundies awards.</html>",
                    "<html>The office reviews its sexual harassment<br>policy in light of explicit e-mails.</html>",
                    "<html>Ready to finalize his deal for a new condo,<br>Michael is away with Dwight while Jim rallies<br>the staff together for office games.</html>",
                    "<html>A fire in the kitchen relegates the staff to<br>the parking lot as help is on its way.</html>",
                    "<html>Michael is pressured by corporate to fire<br>someone, which puts a damper on the office<br>Halloween party.</html>",
                    "<html>Jim rallies the staff together to witness a<br>showdown between Michael and Dwight at<br>Dwight's martial arts school.</html>",
                    "<html>With Michael and Jan Levinson-Gould away from<br>the office to land a new client, the staff<br>discovers an unproduced screenplay in<br>Michael's office.</html>",
                    "<html>Instead of talking to his employees about<br>their work, Michael uses their annual review<br>time to gather feedback on his \"relationship\"<br>with Jan.</html>",
                    "<html>Michael decides to set up e-mail surveillance<br>for all company e-mail, and discovers that<br>Jim has invited everyone over for a barbeque<br>except him.</html>",
                    "<html>Seeing the party is headed for disastrous<br>boredom, Michael breaks corporate policy to<br>buy alcohol for the staff.</html>",
                    "<html>The Dunder Mifflin staff go on a mandatory<br>\"booze cruise\" to hear Michael give a<br>motivational talk.</html>",
                    "<html>Michael's \"injury\" from a George Foreman<br>Grill distracts the staff from Dwight, the<br>one with the real injury.</html>",
                    "<html>Jim fears the secret he told to Michael, in<br>confidence, will be revealed to the staff.</html>",
                    "<html>Michael's office becomes the victim of an<br>odorous prank which subjects the office to<br>his punishment.</html>",
                    "<html>Jan comes into the Scranton Branch to give<br>all the female employees a group seminar on<br>women in the workplace.</html>",
                    "<html>When Michael visits Dunder Mifflin corporate<br>headquarters in New York on Valentine's Day,<br>he and Jan are both in for a surprise.</html>",
                    "<html>Michael coaches pompous Dwight on the finer<br>art of public speaking after being named as<br>Salesman of the Year.</html>",
                    "<html>A routine office day is changed when children<br>come to Dunder Mifflin for \"Take Your<br>Daughter to Work Day\".</html>",
                    "<html>In celebration of his birthday, Michael makes<br>a mandatory invite of the staff during the<br>workday to go ice skating.</html>",
                    "<html>Dwight plays the role of Volunteer Sheriff<br>after finding half a joint in the Dunder<br>Mifflin parking lot leading to an<br>investigation.</html>",
                    "<html>When Michael takes over conflict resolution<br>duties from HR, chaos ensues at Dunder<br>Mifflin.</html>",
                    "<html>The Dunder Mifflin crew holds a casino party<br>at the warehouse and Michael has two dates.</html>"},

            {"<html>Michael apologizes to Oscar, after he finds<br>out he's gay, for calling him a homosexual<br>slur--but his apology outs Oscar to the<br>entire office.</html>",
                    "<html>Michael and Dwight go to a convention in<br>Philadelphia and run into Jim, and Michael<br>becomes jealous of Jim's relationship with<br>his new boss.</html>",
                    "<html>Michael is in trouble once again as Jan busts<br>him for declaring it's \"Movie Monday\" where<br>everyone watches a movie and neglects work.</html>",
                    "<html>Michael takes on the role of office grief<br>counselor when he learns that his old boss<br>has died.</html>",
                    "<html>Dwight takes former temp Ryan to his beet<br>farm to initiate Ryan to his new job at<br>Dunder Mifflin.</html>",
                    "<html>Michael encourages the entire Scranton branch<br>to support Kelly and attend a local<br>celebration of Diwali, the Hindu Festival of<br>Lights.</html>",
                    "<html>When Jan tells Michael that the Scranton<br>Branch will be shutting down, Michael strives<br>to keep his staff's spirits up.</html>",
                    "<html>Jan informs Michael that the Scanton branch<br>of Dunder Mifflin will be merging with the<br>Stamford Branch.</html>",
                    "<html>Michael learns that one of the new employees<br>at Dunder Mifflin Scranton has a criminal<br>record.</html>",
                    "<html>Trouble among the members of the party<br>planning committee results with Pam and Karen<br>hosting a rival Christmas party, but Michael<br>isn't interested in celebrating after being<br>dumped by Carol.</html>",
                    "<html>Trouble among the members of the party<br>planning committee results with Pam and Karen<br>hosting a rival Christmas party, but Michael<br>isn't interested in celebrating after being<br>dumped by Carol.</html>",
                    "<html>Michael isn't supposed to let anyone know<br>that he and Jan went on vacation together in<br>Jamaica, but he accidentally circulates a<br>compromising photo of them to the office via<br>e-mail.</html>",
                    "<html>Dwight does a favor for Angela to keep her<br>from getting in trouble.</html>",
                    "<html>Andy does the impossible--he makes everyone<br>in the office miss Dwight, who is forced to<br>take a job at Staples.</html>",
                    "<html>Michael asks Jim to get a male stripper for<br>Phyllis's office bachelorette party, but he<br>gets a Ben Franklin impersonator instead.</html>",
                    "<html>Michael exaggerates the importance of his<br>small role in Phyllis's wedding and makes an<br>ass out of himself, and Pam notices that<br>Phyllis stole all of her wedding ideas from<br>her original wedding plans.</html>",
                    "<html>Michael is a guest speaker for Ryan's<br>business class, but they have a falling out<br>after Michael finds out that Ryan spoke<br>negatively about Dunder Mifflin.</html>",
                    "<html>While Michael and Jan go to their first<br>Dunder Mifflin outing as an official couple,<br>the office workers left behind go out for<br>happy hour.</html>",
                    "<html>Dwight saves Jim from an attack by Roy, but<br>Dwight won't allow Jim to thank him for it.</html>",
                    "<html>Andy returns to the office after weeks of<br>anger management training, determined to make<br>a fresh start with all the Dunder-Mifflin<br>employees.</html>",
                    "<html>Michael tries to be proactive during a<br>watermark crisis, but only makes the<br>situation worse.</html>",
                    "<html>Phyllis gets flashed in the parking lot, and<br>Dwight goes all out to secure the premises.</html>",
                    "<html>Michael uses \"beach day\" at Dunder-Mifflin to<br>find out which employee would be his most<br>capable replacement, just in case he receives<br>the promotion to the New York office that<br>he's applied for.</html>",
                    "<html>Michael appoints Dwight as regional manager,<br>anticipating that he will receive the job at<br>corporate.</html>",
                    "<html>Michael appoints Dwight as regional manager,<br>anticipating that he will receive the job at<br>corporate.</html>"},

            {"<html>Michael accidentally runs over Meridith in<br>the parking lot, and his guilt causes him to<br>organize a 5-K run for her.</html>",
                    "<html>Michael feels threatened when Ryan returns to<br>the Scranton office to share his ideas about<br>the future of Dunder Mifflin.</html>",
                    "<html>The Dunder Mifflin Infinity website is<br>launching and Michael is excited about going<br>to the big launch party in New York while<br>Angela plans a satellite party for the<br>Scranton branch.</html>",
                    "<html>As Jan renovates the condo, Michael confronts<br>his growing debt every way he can, which<br>includes pressuring his employees for a loan.</html>",
                    "<html>Michael tries to make a local Dunder Mifflin<br>commercial that is better than the one the<br>professional ad agency made for them.</html>",
                    "<html>Michael and Dwight try to play a prank on<br>Karen, who is now manager of the Utica<br>branch, after she tries to steal Stanley from<br>the Scranton office.</html>",
                    "<html>After Michael isn't invited to a camping trip<br>with Ryan, he sets out to prove that he can<br>brave it out in the wilderness by himself.</html>",
                    "<html>Michael is put in an awkward position when<br>Jan sues Dunder Mifflin for wrongful<br>termination and he is deposed as a witness.</html>",
                    "<html>Michael invites Jim and Pam and Andy and<br>Angela to a couples-only dinner party, which<br>makes Dwight very jealous.</html>",
                    "<html>Kevin and Andy team up to reclaim the stolen<br>Dunder Mifflin parking spaces, which forces<br>them into a showdown with the other four<br>bosses of the office park.</html>",
                    "<html>Michael and Dwight go to New York to party<br>with Ryan, who is having lots of personal and<br>professional problems.</html>",
                    "<html>Michael tries to figure out how to respond to<br>Stanley's insubordination during a meeting,<br>and Dwight buys Andy's vehicle and<br>immediately flips it for more money.</html>",
                    "<html>Dunder Mifflin participates in a high school<br>job fair, but few students are interested.</html>",
                    "<html>Michael throws an extravagant going-away<br>party for Toby, and falls in love with the<br>woman who is replacing him.</html>"},

            {"<html>Michael tries to motivate the Scranton branch<br>to lose weight as part of an interoffice<br>competition.</html>",
                    "<html>A confession at an H.R. business ethics<br>seminar leads to a dispute between Michael<br>and Holly over whether Meredith should be fired.</html>",
                    "<html>After planning an office baby shower for Jan,<br>Michael is upset when he finds out that she<br>had the baby without him--even though he's<br>already been told that he's not the baby's<br>father.</html>",
                    "<html>Michael and Holly have sex for the first<br>time, and Michael holds a fundraiser for the<br>office after it is burglarized.</html>",
                    "<html>Holly is transferred back to New Hampshire<br>after corporate discovers that she and<br>Michael are dating.</html>",
                    "<html>Dwight and Jim believe that something is<br>suspicious about their low customer<br>performance ratings.</html>",
                    "<html>David Wallace sends Michael on a business<br>trip to Winnipeg to help him forget about<br>Holly's transfer to Nashua, and Pam tells Jim<br>that she failed a class and has to stay in<br>New York City.</html>",
                    "<html>When Michael discovers that corporate has<br>brought back Toby to replace Holly, he tries<br>to frame him with drugs and to get him fired.</html>",
                    "<html>Michael has to spend the office surplus by<br>they end of the day, but he can't decide<br>between a copier or new chairs.</html>",
                    "<html>Phyllis blackmails Angela into doing the work<br>for the Christmas party, which Michael turns<br>into an intervention after Meredith gets<br>drunk and sets her hair on fire.</html>",
                    "<html>Moments before he leaves for New York for a<br>meeting with David Wallace, Michael tells<br>Andy that Angela and Dwight are seeing each<br>other.</html>",
                    "<html>Michael's conscience gets the best of him<br>after he and Dwight go undercover to scout a<br>family-run competitor.</html>",
                    "<html>Dwight's too-realistic fire alarm gives<br>Stanley a heart attack.</html>",
                    "<html>While on lecture tour to other Dunder Mifflin<br>branches, Michael and Pam discover that Jim's<br>ex-girlfriend Karen is pregnant.</html>",
                    "<html>Michael and Pam go to Nashua and discover<br>that Holly has a new boyfriend.</html>",
                    "<html>Michael holds a lonely hearts party on<br>Valentine's Day at the office, hoping that he<br>will run into a woman he met earlier that day<br>at a blood drive.</html>",
                    "<html>Michael asks Dwight to be the scapegoat for<br>one of his business ideas that backfired<br>badly on him.</html>",
                    "<html>Michael gets upset when he gets a new boss to<br>act as a buffer between him and David<br>Wallace, and he gets even more upset when he<br>disbands the Party Planning Committee and<br>cancels Michael's fifteenth anniversary party.</html>",
                    "<html>As Michael prepares to leave Dunder Mifflin,<br>he announces that he will form his own paper<br>company.</html>",
                    "<html>Michael and Pam begin their first day as the<br>Michael Scott Paper Company putting together<br>the rest of the staff and trying to raise<br>money.</html>",
                    "<html>Tension and disillusionment begin to emerge<br>as Michael, Pam, and Ryan move the Michael<br>Scott Paper Company into a cramped<br>\"workspace\" at the business park.</html>",
                    "<html>Dwight chooses loyalty to Dunder Mifflin over<br>loyalty to Michael, which leads to a bitter<br>battle between Michael and Dwight over<br>Dwight's accounts.</html>",
                    "<html>The Michael Scott Paper Company is gaining<br>clients by offering lower prices than Dunder<br>Mifflin, but is going broke in the process.</html>",
                    "<html>Michael returns to Dunder Mifflin and brings<br>Ryan and Pam in as salespeople, but the<br>existing salespeople demand that Michael<br>return the clients they stole back to them.</html>",
                    "<html>Michael tries to create a place to escape<br>from work in the storage room that used to<br>house the Michael Scott Paper Company, while<br>Jim and Pam consider taking off and getting<br>married that day.</html>",
                    "<html>Michael runs into Holly at the company<br>picnic, and the two of them accidentally<br>reveal that the Buffalo branch is closing<br>during a comedy skit before corporate has<br>made the announcement.</html>"},

            {"<html>Michael regrets revealing that Stanley is<br>having an affair, so he spreads a bunch of<br>lies about everyone else to cover his tracks<br>--except that one of the lies that he spread<br>actually turns out to be true.</html>",
                    "<html>Michael sabotages--then promotes--Jim's<br>efforts at getting a promotion, while Dwight<br>and Toby try to prove that Darryl has<br>submitted a fraudulent medical claim.</html>",
                    "<html>Jim discovers just how hard being the boss<br>can be when David Wallace forces Michael and<br>him to determine which employees will be<br>getting a raise.</html>",
                    "<html>The Office travels to Niagara Falls to<br>celebrate Jim and Pam's wedding under strict<br>orders not to mention Pam's pregnancy.</html>",
                    "<html>Michael meets with an insurance salesman that<br>visits the office and is later convinced by<br>Dwight and Andy that he is part of the mafia.</html>",
                    "<html>Jim and Pam return from their honeymoon and<br>learn, to their horror, that Michael is<br>dating Pam's mom.</html>",
                    "<html>Michael is upset when he becomes the butt of<br>all the office jokes after he falls in a koi<br>pond.</html>",
                    "<html>Michael sparks more anger from Pam when he<br>breaks up with her mom on her birthday after<br>he finds out she's 58, and Dwight<br>unsuccessfully tries to get everyone in the<br>office to owe him a favor.</html>",
                    "<html>The entire office is preoccupied about rumors<br>of Dunder Mifflin's bankruptcy.</html>",
                    "<html>Michael speaks out of line at the Dunder<br>Mifflin shareholders meeting and creates a<br>big problem for management, while Jim<br>discovers that nobody in the office thinks<br>he's the real boss.</html>",
                    "<html>Ten years ago, Michael promised a group of<br>third graders he would pay for their college<br>tuition if they graduated.</html>",
                    "<html>Michael gets upset when Jim promises Phyllis<br>that she can be the office Santa, but the<br>office Christmas party may be overshadowed by<br>some bad news from David Wallace.</html>",
                    "<html>A banker representing a potential buyer comes<br>to the Scranton branch to interview the H.R.<br>department before the sale goes through.</html>",
                    "<html>Michael hates the changes that Dunder<br>Mifflin's new owner is implementing, so he<br>turns to David Wallace for advice.</html>",
                    "<html>Sabre's CEO wants the Scranton branch to have<br>one manager, and Michael voluntarily steps<br>down and lets Jim become the boss when he<br>finds out that salespeople make more money.</html>",
                    "<html>Pam goes into labor and Jim is ready to take<br>her to the hospital, but she refuses to go.</html>",
                    "<html>After the baby is born, Pam has trouble<br>getting the baby to breastfeed.</html>",
                    "<html>It's St. Patrick's Day, and the CEO forces<br>the office to work late because she won't leave.</html>",
                    "<html>When the sales staff begins trying to boss<br>around everyone in the office, Michael tries<br>to teach them a lesson by withholding a<br>valuable set of sales leads.</html>",
                    "<html>Oscar gets everybody in the office to go to<br>Happy Hour so that he can hit on a coworker<br>in shipping.</html>",
                    "<html>Michael creates problems for Andy on<br>Secretary's Day when he tells Erin that Andy<br>was engaged to Angela, and Kevin is upset<br>after Oscar makes a video comparing Kevin to<br>Cookie Monster.</html>",
                    "<html>Michael is hopeful that a potential client is<br>interested in him, but everyone in the office<br>except Pam thinks he's wasting his time.</html>",
                    "<html>Michael becomes convinced that Donna is<br>having an affair and puts Dwight on the case,<br>but Pam soon discovers that the suspicions<br>may be true.</html>",
                    "<html>Michael continues to see Donna even after<br>learning she's married and meeting her<br>husband, Dwight and Angela take their baby<br>contract to an arbitrator, and Jim and Pam<br>struggle to stay awake at the office.</html>",
                    "<html>Jo comes to the Scranton branch to find the<br>whistle-blower.</html>"},

            {"<html>Everybody demands that Michael fire the new<br>office assistant, but he won't because he's<br>his nephew.</html>",
                    "<html>Michael is forced to go through counseling<br>with Toby, Dwight seeks revenge on a local<br>mall that refused his business, and Pam tries<br>to fake her way to a promotion.</html>",
                    "<html>Andy invites the entire office to watch him<br>in the community theater production of<br>\"Sweeney Todd\", but Erin decides to babysit<br>for Jim and Pam instead.</html>",
                    "<html>A herpes scare causes Michael to get back in<br>touch with his ex-girlfriends, where he<br>decides to reevaluate those relationships.</html>",
                    "<html>Michael organizes a sting operation to find<br>out the secrets of a rival paper company's<br>salesman who is stealing Dunder Mifflin's<br>clients, and Andy gets Darryl's help to form<br>a band.</html>",
                    "<html>It's Halloween at Dunder Mifflin, and Michael<br>is upset that Darryl went over his head with<br>an idea.</html>",
                    "<html>During Jim and Pam's daughter's christening,<br>Michael becomes upset over the lack of<br>family-like unity between himself and his<br>employees.</html>",
                    "<html>Michael sabotages Erin's \"Glee\" viewing party<br>because of his contempt for Gabe, Jim and Pam<br>discover that Dwight can keep their daughter<br>from crying, and Andy has a bad reaction to a<br>mixture of wine and a Japanese stimulant.</html>",
                    "<html>Some co-workers who invested in Ryan's<br>Internet venture want him to sell, but<br>Michael refuses to go along.</html>",
                    "<html>Pam stands up to Dwight when he makes<br>cutbacks to save money in the building, but<br>will Dwight have the last laugh?</html>",
                    "<html>Michael throws an elaborate Christmas party<br>to celebrate Holly's temporary return to the<br>Scranton branch, but is disappointed when he<br>learns that she still has a boyfriend.</html>",
                    "<html>Michael throws an elaborate Christmas party<br>to celebrate Holly's temporary return to the<br>Scranton branch, but is disappointed when he<br>learns that she still has a boyfriend.</html>",
                    "<html>Michael gets upset when Holly returns from<br>the holidays without an engagement ring, but<br>still together with her boyfriend.</html>",
                    "<html>Andy tries to host a small business seminar<br>at the office.</html>",
                    "<html>When Jim gets an emergency phone call from<br>Helene, he is forced to leave Michael in the<br>bathroom of a gas station.</html>",
                    "<html>It's Valentine's Day, and the office is fed<br>up with Michael and Holly's PDA, Andy helps<br>Erin solve Gabe's riddles to find her gift,<br>and Jim and Pam get drunk and try to find a<br>place in the office to have sex.</html>",
                    "<html>Michael finally finishes his movie \"Threat<br>Level Midnight\" and screens it for his<br>employees at Dunder Mifflin, but Holly is<br>less than enthusiastic for his finished<br>product.</html>",
                    "<html>Everyone is up in arms after Michael<br>convinces Holly to give Todd Packer an office<br>job, and Andy gets upset after Pam gets a new<br>computer for reception but not for him.</html>",
                    "<html>Michael plans to propose to Holly the day of<br>the Dunder Mifflin garage sale, but Holly may<br>have to take an extended leave of absence to<br>Colorado because her father is sick.</html>",
                    "<html>Michael makes fast friends with the man<br>coming in to replace him at Dunder Mifflin,<br>but later begins to have second thoughts<br>after seeing him in action.</html>",
                    "<html>Michael hosts his final \"Dundies\" as the boss<br>at the Scranton branch, but tension is in the<br>air, and Deangelo Vickers, the new boss, is<br>having trouble with his co-hosting duties.</html>",
                    "<html>As the office gets ready for Michael's final<br>day at Dunder Mifflin, Michael doesn't tell<br>anyone that he's leaving a day early.</html>",
                    "<html>Tensions rise and feelings are hurt when<br>Deangelo creates an \"inner circle\" at the<br>office--which is only composed of men.</html>",
                    "<html>When Jim rejects Jo's offer, Dwight becomes<br>acting manager at the Scranton branch, but an<br>accident could cause his tenure to be short-<br>lived.</html>",
                    "<html>The Scranton branch puts together a search<br>committee to find the next boss, but the pool<br>of interviewees proves to be less than<br>impressive, and Dwight demands an interview<br>in spite of his gun accident.</html>",},

            {"<html>New Dunder Mifflin CEO Robert California<br>leaves a piece of paper with a line down the<br>middle that has names of the Scranton staff<br>on either side of it, leading everyone to try<br>and figure out what it means.</html>",
                    "<html>Under pressure from Robert to increase branch<br>sales, Andy offers an incentive program to<br>the sales staff, which backfires on him when<br>he offers a very personal grand prize.</html>",
                    "<html>After the entire warehouse staff wins the<br>lottery and quits their job, Darryl becomes<br>depressed and demands to be fired.</html>",
                    "<html>Andy claims to be throwing a garden party at<br>Dwight's farm to impress Robert California,<br>but he's really doing it to win the approval<br>of his parents, who appear to favor his<br>younger brother.</html>",
                    "<html>Erin is worried that she is about to get<br>fired after she organizes a disastrous office<br>Halloween party for Robert and his son.</html>",
                    "<html>Dwight installs a \"Doomsday Device\" on the<br>office computers that could get everyone<br>fired if they make too many mistakes, while<br>Gabe tries to hit on one of Darryl's<br>warehouse employees.</html>",
                    "<html>A pregnant and insecure Pam tries to prove<br>that Jim is attracted to her temp<br>replacement, and Robert and his musician<br>friends take over a jam session with Andy,<br>Kevin, and Darryl.</html>",
                    "<html>Andy decides to motivate and inspire everyone<br>by taking them on a field trip to Gettysburg.</html>",
                    "<html>Robert brings his wife to the office so that<br>she can find a job, but he gives Andy<br>conflicting messages about whether to hire<br>her.</html>",
                    "<html>Andy tries to make this year's Christmas the<br>best ever by granting each person's holiday<br>wishes.</html>",
                    "<html>Andy hopes to make up for a sales deficiency<br>by entering and winning a bar trivia<br>competition, while Dwight flies to corporate<br>headquarters in Florida to demand a<br>management interview with Robert.</html>",
                    "<html>Robert throws a party for the Dunder Mifflin<br>staff at his house before he sells it because<br>of his divorce.</html>",
                    "<html>Jim gets caught in a lie about his week of<br>\"jury duty\", and new questions emerge when<br>Angela gives birth to a \"premature\" baby.</html>",
                    "<html>Andy puts Dwight in charge of a special<br>project in Tallahassee, but Dwight doesn't<br>like the team Andy's assembled for him.</html>",
                    "<html>Dwight refuses to let appendicitis get in the<br>way of leading his new team in Tallahassee,<br>while Andy decides to step in for Erin as<br>secretary in the office.</html>",
                    "<html>In Tallahassee, Dwight and Todd Packer try to<br>romance Nellie to get the VP position, while<br>Jim wonders if Kathy is trying to hit on him.</html>",
                    "<html>Dwight and his team get ready for the grand<br>opening of the Sabre Store, while Andy makes<br>Toby teach self-defense to the Scranton<br>branch employees after he is beat up in the<br>parking lot by a girl.</html>",
                    "<html>Jim tries to warn Dwight that he's going to<br>be fired after Robert rejects the Sabre Store<br>idea, but he refuses to listen.</html>",
                    "<html>Andy goes to Tallahassee to tell Erin that he<br>loves her and needs her to return to Scranton.</html>",
                    "<html>Andy tries to break up with his girlfriend<br>after going to Florida to declare his love<br>for Erin, and the office employees are forced<br>against their will to throw a party for the<br>hated Nellie.</html>",
                    "<html>Andy and Erin return to Dunder Mifflin, only<br>to discover that Nellie has taken his job and<br>office and refuses to give them up.</html>",
                    "<html>Andy confronts Robert for the first time<br>after losing the manager position and<br>quitting his job at a fund raiser sponsored<br>by Angela's husband.</html>",
                    "<html>Dwight and Jim fight with the Syracuse over a<br>client after Robert shuts down the Binghamton<br>branch, and Andy sees an opportunity for<br>revenge.</html>",
                    "<html>With former CEO David Wallace's help, Andy<br>launches a plan to get revenge on the<br>Scranton branch.</html>"},

            {"<html>Dwight and Jim are intimidated by the<br>office's newest additions, who are considered<br>younger versions of themselves.</html>",
                    "<html>After Roy's wedding, Jim and Pam wonder if<br>they still have any secrets they're hiding<br>from each other.</html>",
                    "<html>Nellie plays a trick on Andy after<br>researching his ancestry, Dwight teaches Erin<br>a new language, and Pam tries to teach Nellie<br>how to drive.</html>",
                    "<html>When Jim convinces Dwight that the building<br>is unsafe, Dwight rents a bus and sets up the<br>office inside.</html>",
                    "<html>On Halloween, the Cornell a Capella group<br>pays a visit to Andy, Dwight discovers that<br>Nellie takes anxiety pills, and Pam<br>disapproves of Jim's business decision.</html>",
                    "<html>Andy has one last chance to captain the<br>family boat before he sells it, Jim, Pam, and<br>Nellie prank Dwight with a radio interview,<br>and Kevin finds out about Oscar's affair with<br>Angela's husband.</html>",
                    "<html>The office trains Dwight to sell to a female<br>client without being offensive, only to<br>discover that the client is Jan Levinson.</html>",
                    "<html>Angela orders a hit on Oscar for cheating<br>with her husband, the office makes a tower<br>with their customer complaint cards, Jim<br>wines and dines Stanley and Phyllis in<br>exchange for a favor, and Pam begins her<br>mural.</html>",
                    "<html>Dwight puts together a Pennsylvania Dutch-<br>themed office Christmas party, but he ends it<br>abruptly because Jim has to leave for his<br>other job.</html>",
                    "<html>Pam causes a lice outbreak but lets Meredith<br>take the blame, Jim has a business meeting<br>with Dr. J, and some coworkers try to get<br>Darryl and Val back together.</html>",
                    "<html>Dwight and Clark pose as father and son to<br>get an account, Darryl goes for an interview<br>with Jim's new business, and everybody in the<br>office goes crazy over a new espresso machine.</html>",
                    "<html>Dwight tries to keep Darryl from leaving<br>Dunder Mifflin, Jim misses his daughter's<br>recital because of an important business<br>meeting, and Nellie is worried that Erin will<br>dump Andy for Pete.</html>",
                    "<html>Dwight gets to hire a new salesman to replace<br>Jim when he is at his other job.</html>",
                    "<html>Pam tries to find out who vandalized her<br>mural, Darryl finds out that Jim is a slob,<br>and Oscar and Kevin go to Angela and The<br>Senator's child's first birthday party.</html>",
                    "<html>Andy returns after three months to an angry<br>office and an even angrier girlfriend, and<br>Jim's Valentines Day with Pam does not go as<br>planned.</html>",
                    "<html>Andy finds out that Erin dumped him for Pete,<br>Dwight gets Angela's help taking care of his<br>aunt, and Pam interviews with a real estate<br>firm whose boss is a carbon-copy of Michael<br>Scott.</html>",
                    "<html>Show follows Dwight Schrute a beet farmer<br>running a bed and breakfast inn.</html>",
                    "<html>The release of the documentary promos creates<br>tension for the Dunder Mifflin employees,<br>Dwight considers a business venture with his<br>girlfriend's family, and Jim and Darryl have<br>an awkward business meeting with baseball<br>player Ryan Howard.</html>",
                    "<html>Dwight shoots Stanley with a bull<br>tranquilizer after he refuses to go on a<br>sales call, Jim and Pam head to marriage<br>counseling, The Senator comes out of the<br>closet, and Andy tries to find a talent agent.</html>",
                    "<html>The employees hold a paper airplane<br>competition, Andy gets an acting role in a<br>workplace safety video, and Jim and Pam's<br>marriage tensions continue to build.</html>",
                    "<html>Dwight becomes regional manager after Andy<br>quits his job, Jim dedicates more time to his<br>Dunder Mifflin job to save his marriage, and<br>Angela has problems with her new living<br>arrangements after her breakup with The<br>Senator.</html>",
                    "<html>Dwight prepares for a marriage proposal and<br>hires an assistant for his assistant, Andy<br>auditions for a singing program, Darryl tries<br>to leave his job without a fuss, and Pam has<br>second thoughts about Jim staying in Scranton.</html>",
                    "<html>One year later, Dunder Mifflin employees past<br>and present reunite for a panel discussion<br>about the documentary and to attend Dwight<br>and Angela's wedding.</html>"}
    };

    static int[][] dur = {
            {(23*60+2), (21*60+47), (22*60+2), (21*60+58), (22*60+3), (22*60+5)},
            {(20*60+50), (21*60+33), (21*60+27), (21*60+23), (21*60+52), (21*60+52), (21*60+31), (21*60+30), (22*60+2),
                    (21*60+45), (21*60+4), (21*60+8), (21*60+7), (21*60+6), (21*60+20), (21*60+9), (21*60+9),
                    (20*60+58), (21*60+7), (21*60+8), (21*60+8), (28*60+20)},
            {(21*60+57), (21*60+27), (21*60+5), (21*60+11), (21*60+11), (21*60+10), (30*60+14), (30*60+43), (21*60+11),
                    (21*60+50), (20*60+0), (21*60+10), (21*60+26), (28*60+25), (21*60+11), (21*60+11), (21*60+42),
                    (21*60+45), (29*60+28), (21*60+11), (21*60+19), (28*60+53), (27*60+53), (21*60+23), (21*60+8)},
            {(41*60+58), (41*60+59), (41*60+59), (41*60+58), (21*60+35), (21*60+50), (21*60+15), (21*60+33), (22*60+16),
                    (21*60+47), (21*60+17), (22*60+03), (20*60+46), (41*60+59)},
            {(42*60+1), (21*60+39), (21*60+36), (21*60+36), (21*60+38), (21*60+47), (21*60+39), (25*60+49), (21*60+51), (21*60+38),
                    (21*60+38), (21*60+39), (41*60+35), (21*60+39), (21*60+54), (21*60+39), (21*60+38), (21*60+39), (21*60+37),
                    (21*60+28), (21*60+38), (21*60+38), (21*60+38), (21*60+38), (21*60+39), (21*60+38)},
            {(21*60+24), (21*60+30), (21*60+31), (42*60+8), (21*60+32), (21*60+26), (21*60+26), (21*60+27), (21*60+25), (21*60+26),
                    (21*60+27), (21*60+33), (21*60+27), (21*60+30), (21*60+25), (21*60+46), (20*60+35), (21*60+28),
                    (21*60+26), (21*60+26), (21*60+28), (21*60+32), (21*60+24), (22*60+7), (21*60+29)},
            {(22*60+6), (22*60+5), (22*60+9), (22*60+7), (22*60+7), (22*60+5), (22*60+6), (22*60+6), (22*60+8), (22*60+13), (21*60+28),
                    (21*60+34), (22*60+7), (22*60+7), (22*60+6), (22*60+6), (22*60+8), (22*60+8), (22*60+7), (22*60+7),
                    (22*60+8), (36*60+14), (22*60+6), (22*60+5), (55*60+54)},
            {(22*60+8), (22*60+9), (22*60+7), (22*60+6), (22*60+7), (22*60+6), (22*60+9), (22*60+8), (22*60+8), (22*60+8),
                    (22*60+9), (22*60+7), (22*60+6), (22*60+8), (22*60+6), (22*60+8), (22*60+9), (22*60+6), (22*60+8),
                    (22*60+7), (33*60+20), (25*60+50), (22*60+6), (22*60+8)},
            {(22*60+10), (22*60+6), (22*60+11), (22*60+2), (22*60+4), (22*60+4), (22*60+6), (22*60+1), (22*60+3), (22*60+2),
                    (21*60+59), (22*60+3), (22*60+2), (22*60+1), (22*60+1), (41*60+31), (22*60+3), (22*60+3), (22*60+1),
                    (22*60+3), (40*60+31), (43*60+14), (51*60+5)}
    };

    public static int[] current = new int[3];
}
